/**
 * Catalog rows for Prisma seed. Sync from products.json (dedupe by slug, last wins).
 * Images: public/products/images/ — filenames have no spaces.
 */
export type CatalogProductSeed = {
  slug: string;
  name: string;
  description: string;
  price: number;
  imageUrl: string;
  rating: number;
};

function productImageUrl(path: string): string {
  const t = path.trim();
  if (t.startsWith("/products/images/")) return t;
  if (t.startsWith("/images/")) return "/products/images/" + t.slice("/images/".length);
  const f = t.replace(/^\//, "");
  return "/products/images/" + (f.split("/").pop() ?? f);
}

export const CATALOG_PRODUCTS: CatalogProductSeed[] = [
  {
    slug: "5-amino-1mq-5mg",
    name: "5 Amino 1Q 5MG",
    description: "5-Amino-1MQ is a compound studied for its potential role in fat metabolism and cellular energy pathways. Supplied as 5mg for controlled research and laboratory testing. For research use only.",
    price: 150,
    imageUrl: productImageUrl("/images/Amino1Q-01.jpg"),
    rating: 4.7,
  },
  {
    slug: "bpc-157-10mg",
    name: "BPC-157 10MG",
    description: "BPC-157 is a synthetic peptide studied in laboratory settings for its role in tissue repair, recovery processes, and cellular regeneration. The 10mg formulation is supplied for controlled experimental applications and consistent research outcomes. For research use only.",
    price: 120,
    imageUrl: productImageUrl("/images/BPC15710mg-01.jpg"),
    rating: 4.8,
  },
  {
    slug: "bpc-157-5mg",
    name: "BPC-157 5MG",
    description: "BPC-157 in 5mg concentration provides flexibility for precision-based research studies. It is commonly investigated for its potential involvement in tissue regeneration and recovery-focused laboratory experiments. For research use only.",
    price: 90,
    imageUrl: productImageUrl("/images/BPC157-01.jpg"),
    rating: 4.7,
  },
  {
    slug: "bpc157-10mg",
    name: "BPC-157 Peptide 10mg",
    description: "BPC-157 10mg is a higher concentration peptide used in research related to healing, inflammation, and angiogenesis. Frequently studied in experimental models for regenerative medicine. High purity ensures reliable outcomes. For research use only. Not for human consumption.",
    price: 120,
    imageUrl: productImageUrl("/images/8.jpg"),
    rating: 4.8,
  },
  {
    slug: "bpc157-5mg",
    name: "BPC-157 Peptide 5mg",
    description: "BPC-157 is a research peptide derived from gastric proteins and studied for its regenerative properties. Commonly used in laboratory research focusing on tissue repair, angiogenesis, and inflammation. High purity formulation ensures consistent experimental results. For research use only. Not for human consumption.",
    price: 95,
    imageUrl: productImageUrl("/images/5.jpg"),
    rating: 4.9,
  },
  {
    slug: "bpc157-tb500-10mg",
    name: "BPC157 (5mg) + TB500 (5mg) 10MG",
    description: "A balanced combination of BPC-157 and TB500 designed for controlled-dose research environments. This 10mg formulation is commonly used in studies related to recovery, repair processes, and peptide interaction effects. For research use only.",
    price: 140,
    imageUrl: productImageUrl("/images/BPC157(5mg)+-01.jpg"),
    rating: 4.7,
  },
  {
    slug: "bpc157-tb500-10mg-blend",
    name: "BPC-157 5mg + TB-500 5mg",
    description: "This peptide blend combines BPC-157 and TB-500 for research involving tissue repair and recovery mechanisms. Often studied for synergistic effects in regenerative biology and inflammation reduction. Manufactured for precision and purity. For research use only. Not for human consumption.",
    price: 140,
    imageUrl: productImageUrl("/images/6.jpg"),
    rating: 4.8,
  },
  {
    slug: "bpc157-tb500-20mg",
    name: "BPC157 (10mg) + TB500 (10mg) 20MG",
    description: "This peptide blend combines BPC-157 and TB500, both widely studied for their potential roles in recovery and cellular repair mechanisms. The 20mg formulation is intended for advanced laboratory research focusing on regeneration and tissue response. For research use only.",
    price: 180,
    imageUrl: productImageUrl("/images/BPC157(5mg)+20-01.jpg"),
    rating: 4.9,
  },
  {
    slug: "bpc157-tb500-20mg-blend",
    name: "BPC-157 10mg + TB-500 10mg",
    description: "A high-dose peptide blend designed for advanced laboratory research. Combines 10mg BPC-157 and 10mg TB-500 for extended studies in tissue regeneration, healing processes, and cellular repair. Produced with strict quality control. For research use only. Not for human consumption.",
    price: 180,
    imageUrl: productImageUrl("/images/7.jpg"),
    rating: 4.9,
  },
  {
    slug: "cagrilintide-5mg",
    name: "Cagrilintide 5MG",
    description: "Cagrilintide is a long-acting peptide analog studied for its role in appetite regulation and metabolic response mechanisms. The 5mg version is supplied for controlled laboratory testing and research applications. For research use only.",
    price: 160,
    imageUrl: productImageUrl("/images/Cagrilintide-01.jpg"),
    rating: 4.8,
  },
  {
    slug: "cjc-ipa-no-dac-10mg",
    name: "CJC-1295 + Ipamorelin (No DAC) 10mg",
    description: "This peptide blend combines CJC-1295 (No DAC) and Ipamorelin, commonly studied for their synergistic effects on growth hormone release. Used in laboratory research focused on endocrine function, recovery, and muscle development. The 10mg formulation allows precise dosing and controlled experimental use. Manufactured with strict quality control to ensure purity and consistency. For research use only. Not for human consumption.",
    price: 160,
    imageUrl: productImageUrl("/images/33.jpg"),
    rating: 4.9,
  },
  {
    slug: "cjc-ipamorelin-10mg",
    name: "CJC-1295 + Ipamorelin (No DAC) 10MG",
    description: "This combination of CJC-1295 (No DAC) and Ipamorelin is studied for its effects on growth hormone release and recovery mechanisms in laboratory environments. The 10mg formulation supports controlled experimental research. For research use only.",
    price: 170,
    imageUrl: productImageUrl("/images/Cjcipa10mgnodac-01.jpg"),
    rating: 4.9,
  },
  {
    slug: "ghk-cu-50mg",
    name: "GHK-Cu 50MG",
    description: "GHK-Cu is a copper peptide researched for its potential role in skin regeneration, collagen production, and cellular repair. This 50mg formulation is intended for cosmetic and laboratory research use. For research use only.",
    price: 200,
    imageUrl: productImageUrl("/images/GHK-cu-01.jpg"),
    rating: 4.9,
  },
  {
    slug: "glow-70mg",
    name: "GLOW 70MG",
    description: "GLOW is a multi-peptide formulation studied for skin health, anti-aging, and cellular rejuvenation research. The 70mg blend is designed for laboratory testing and experimental applications. For research use only.",
    price: 190,
    imageUrl: productImageUrl("/images/GLOW-01.jpg"),
    rating: 4.8,
  },
  {
    slug: "glp-1s-20mg",
    name: "GLP-1S 20MG",
    description: "GLP-1S is a peptide analog studied for its involvement in glucose metabolism and appetite regulation. This 20mg product is supplied for research focusing on metabolic pathways and energy balance. For research use only.",
    price: 210,
    imageUrl: productImageUrl("/images/GLP-1S-01.jpg"),
    rating: 4.9,
  },
  {
    slug: "glp-r3-10mg",
    name: "GLP-R3 10mg",
    description: "GLP-R3 is a modified peptide studied for metabolic and glucose regulation pathways. 10mg vial. Research use only.",
    price: 180,
    imageUrl: productImageUrl("/images/GLP-R3-01.jpg"),
    rating: 4.8,
  },
  {
    slug: "glp-r3-20mg",
    name: "GLP-R3 20MG",
    description: "GLP-R3 is a research peptide studied for metabolic and energy regulation pathways. The 20mg formulation is intended for laboratory testing and controlled experimental studies. For research use only.",
    price: 220,
    imageUrl: productImageUrl("/images/GLP-R320mg-01.jpg"),
    rating: 4.8,
  },
  {
    slug: "glp-r3-30mg",
    name: "GLP-R3 30MG",
    description: "This higher-dose GLP-R3 peptide is used in advanced research focusing on metabolic function and energy regulation. The 30mg version is designed for extended laboratory studies. For research use only.",
    price: 250,
    imageUrl: productImageUrl("/images/GLP-R330mg-01.jpg"),
    rating: 4.9,
  },
  {
    slug: "glp-t2-20mg",
    name: "GLP-T2 20mg",
    description: "GLP-T2 peptide variant for metabolic research. 20mg vial for laboratory testing. Not for human use.",
    price: 190,
    imageUrl: productImageUrl("/images/GLP-T220mg-01.jpg"),
    rating: 4.8,
  },
  {
    slug: "glp-t2-30mg",
    name: "GLP-T2 30mg",
    description: "Higher concentration GLP-T2 peptide used in advanced metabolic studies. 30mg vial. Research use only.",
    price: 210,
    imageUrl: productImageUrl("/images/GLP-T230mg-01.jpg"),
    rating: 4.9,
  },
  {
    slug: "glp-t2-40mg",
    name: "GLP-T2 40mg",
    description: "Premium GLP-T2 variant for extended research experiments. 40mg vial. Not for human consumption.",
    price: 230,
    imageUrl: productImageUrl("/images/GLP-T240mg-01.jpg"),
    rating: 4.9,
  },
  {
    slug: "igf-1-lr3-1mg",
    name: "IGF-1 LR3 1mg",
    description: "IGF-1 LR3 is a long-acting insulin-like growth factor studied for cell growth and anabolic pathways. 1mg vial. Research use only.",
    price: 200,
    imageUrl: productImageUrl("/images/IGFLR3-01.jpg"),
    rating: 4.9,
  },
  {
    slug: "igf-lr3-1mg",
    name: "IGF-1 LR3 1mg",
    description: "IGF-1 LR3 (Insulin-like Growth Factor Long R3) is a modified peptide widely studied for its role in cell growth, regeneration, and anabolic processes. This 1mg vial is commonly used in laboratory research focused on muscle development, tissue repair, and cellular proliferation. Due to its extended half-life compared to standard IGF-1, it allows researchers to study prolonged biological effects and signaling pathways. Produced under strict laboratory conditions to ensure high purity and reliability. Suitable for advanced peptide research environments. For research use only. Not for human consumption.",
    price: 150,
    imageUrl: productImageUrl("/images/23.jpg"),
    rating: 4.9,
  },
  {
    slug: "klow-80mg",
    name: "KLOW 80mg",
    description: "KLOW is a research peptide studied for metabolic and cellular response mechanisms. Supplied as 80mg for controlled laboratory testing. For research use only.",
    price: 180,
    imageUrl: productImageUrl("/images/Klow-01.jpg"),
    rating: 4.8,
  },
  {
    slug: "kpv-10mg",
    name: "KPV 10mg",
    description: "KPV peptide is commonly researched for anti-inflammatory and immune modulation properties in lab environments. 10mg vial. Research use only.",
    price: 120,
    imageUrl: productImageUrl("/images/KPV-01.jpg"),
    rating: 4.7,
  },
  {
    slug: "lipo-c-b12-10ml",
    name: "LIPO-C w B12 10ml",
    description: "LIPO-C with B12 is a research compound studied for metabolic support and fat metabolism pathways. Supplied in 10ml liquid form. Research use only.",
    price: 150,
    imageUrl: productImageUrl("/images/LIPO-CwB12-01.jpg"),
    rating: 4.6,
  },
  {
    slug: "lipo-c-b12-10ml-2",
    name: "Lipo-C with B12 10ml",
    description: "This lipotropic formulation with Vitamin B12 is used in laboratory studies focused on metabolic processes and energy conversion. Researchers utilize it in controlled environments to analyze fat metabolism and nutrient interactions. Produced with strict quality control for consistency. For research use only. Not for human consumption.",
    price: 90,
    imageUrl: productImageUrl("/images/3.jpg"),
    rating: 4.6,
  },
  {
    slug: "mots-c-10mg",
    name: "MOTS-C 10mg",
    description: "MOTS-C is a mitochondrial-derived peptide studied for metabolic regulation and cellular energy balance. 10mg vial for research purposes only.",
    price: 170,
    imageUrl: productImageUrl("/images/Mots-C-01.jpg"),
    rating: 4.8,
  },
  {
    slug: "mt1-10mg",
    name: "MT1 10mg",
    description: "Melanotan 1 (MT1) is studied for pigmentation pathways and UV response in research environments. 10mg vial. Not for human consumption.",
    price: 110,
    imageUrl: productImageUrl("/images/Mt1-01.jpg"),
    rating: 4.6,
  },
  {
    slug: "mt2-10mg",
    name: "MT2 10mg",
    description: "Melanotan 2 (MT2) is a synthetic peptide researched for melanogenesis and receptor interaction studies. 10mg vial. Research use only.",
    price: 110,
    imageUrl: productImageUrl("/images/Mt2-01.jpg"),
    rating: 4.6,
  },
  {
    slug: "nad-500mg-10ml",
    name: "NAD+ 500mg 10ml",
    description: "NAD+ is a coenzyme researched for cellular energy production and aging-related studies. Supplied in 500mg / 10ml format. Research use only.",
    price: 200,
    imageUrl: productImageUrl("/images/NAD500mg-01.jpg"),
    rating: 4.9,
  },
  {
    slug: "selank-10mg",
    name: "Selank 10mg",
    description: "Selank peptide is researched for cognitive and anxiolytic pathways in laboratory studies. 10mg vial. Not for human use.",
    price: 130,
    imageUrl: productImageUrl("/images/Selank-01.jpg"),
    rating: 4.7,
  },
  {
    slug: "semax-10mg",
    name: "Semax 10mg",
    description: "Semax is studied for neuroprotective and cognitive enhancement pathways. Supplied in 10mg vial for research purposes only.",
    price: 130,
    imageUrl: productImageUrl("/images/Semax-01.jpg"),
    rating: 4.7,
  },
  {
    slug: "sqs-p4-10mg",
    name: "SQS-P4 10mg",
    description: "SQS-P4 is a proprietary research peptide formulation studied for specialized laboratory applications. 10mg vial. Research use only.",
    price: 140,
    imageUrl: productImageUrl("/images/SQS-P410-01.jpg"),
    rating: 4.6,
  },
  {
    slug: "sqs-t1som-10mg",
    name: "SQS-T1SOM 10mg",
    description: "SQS-T1SOM is a synthetic research compound designed for advanced peptide studies. 10mg vial. Not for human consumption.",
    price: 150,
    imageUrl: productImageUrl("/images/SQS-T1SOM-01.jpg"),
    rating: 4.6,
  },
  {
    slug: "ss-31-10mg",
    name: "SS-31 10mg",
    description: "SS-31 is a mitochondrial-targeting peptide researched for cellular protection and oxidative stress studies. 10mg vial. Research use only.",
    price: 160,
    imageUrl: productImageUrl("/images/SS31-01.jpg"),
    rating: 4.8,
  },
  {
    slug: "ss31-10mg",
    name: "SS-31 Peptide 10mg",
    description: "SS-31 is a mitochondria-targeting peptide studied for its effects on cellular energy and oxidative stress. Used in laboratory research related to metabolic efficiency and mitochondrial health. High purity for reliable results. For research use only. Not for human consumption.",
    price: 150,
    imageUrl: productImageUrl("/images/12.jpg"),
    rating: 4.8,
  },
  {
    slug: "tb500-10mg",
    name: "TB-500 10mg",
    description: "TB-500 is a synthetic peptide studied for tissue repair and regeneration in research settings. 10mg vial. Not for human consumption.",
    price: 170,
    imageUrl: productImageUrl("/images/TB50010mg-01.jpg"),
    rating: 4.9,
  },
  {
    slug: "tb500-5mg",
    name: "TB-500 5mg",
    description: "Lower dosage TB-500 variant for controlled experimental research. 5mg vial. For laboratory use only.",
    price: 120,
    imageUrl: productImageUrl("/images/TB500-01.jpg"),
    rating: 4.7,
  },
  {
    slug: "test-e-250-10ml",
    name: "Test E 250 (Legends) 10ml",
    description: "Testosterone Enanthate 250 is studied in hormonal and anabolic research contexts. Supplied in 10ml format. Research use only.",
    price: 220,
    imageUrl: productImageUrl("/images/TestE250legends-01.jpg"),
    rating: 4.8,
  },
];
